# Generated by Django 3.2 on 2024-02-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'join'), (2, 'leave'), (3, 'delete'), (4, 'msg')], default=4),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.groupchat'),
        ),
    ]
