# Generated by Django 3.2 on 2024-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochat',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
